name: Discord Notification

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install discord.js

      - name: Notify Discord
        run: node .github/scripts/discord-notification.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: YOUR_DISCORD_CHANNEL_ID
